Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'builddb'
    - 'rflickr'
  Enabled: true

Style/DateTime:
  Exclude:
    - 'builddb'
    - 'rflickr'
  Enabled: true

Layout/AlignHash:
  Exclude:
    - 'rflickr'
  Enabled: true

