#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pp'
require 'optparse'
require 'ostruct'
require 'find'
require 'open3'
require 'dbm'
require 'date'
require 'oj'

excl = []
o = OpenStruct.new
OptionParser.new do |opts|
  opts.on('-i IMAGES', 'Path to images') { |i| o.i = i }
  opts.on('-e EXCLUDE', 'Exclude paths') { |e| excl << e }
  opts.on('-v', 'Verbose')               { o.v = true }
end.parse!
excl = excl.empty? ? nil : excl.join('|')

abort('provide path to images') unless o.i
abort("not a directory: #{o.i}") unless File.directory?(o.i)

db = DBM.open('photo', 0o644, DBM::WRCREAT)

Find.find(o.i) do |path|
  next unless File.directory?(path)
  next if excl && /(#{excl})/ =~ path

  puts path if o.v
  cmd = %(exiftool -j -createdate "#{path}")
  out, err, st = Open3.capture3 cmd
  unless st.success?
    warn "ERR: #{dir} #{err} #{st}"
    next
  end
  if out.empty?
    puts 'empty' if o.v
    next
  end
  begin
    jfiles = Oj.load out
  rescue Oj::ParseError => e
    warn "bad json? #{e}"
    next
  end

  jc = 0
  jfiles.each do |f|
    file = f['SourceFile']
    next if file.match?(/\.xmp$/i)

    d = f['CreateDate'] || next
    begin
      date = DateTime.strptime(d, '%Y:%m:%d %H:%M:%S')
    rescue ArgumentError => e
      warn "bad date format: #{path} #{d} #{e}"
      next
    end
    puts "#{file} #{date}" if o.v
    db[date.to_time.to_i.to_s] = file
    jc += 1
  end
  puts "stored: #{jc}" if o.v
end

db.close
