#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'
require 'active_support/core_ext/hash'
require 'flickraw'

cfg = YAML.load(File.read "#{__dir__}/flickr.yml").deep_symbolize_keys
FlickRaw.api_key = cfg[:api][:key]
FlickRaw.shared_secret = cfg[:api][:secret]

token = flickr.get_request_token
auth_url = flickr.get_authorize_url(token['oauth_token'], :perms => 'read')

puts "Open this url in your process to complete the authication process : #{auth_url}"
puts "Copy here the number given when you complete the process."
verify = gets.strip

begin
  flickr.get_access_token(token['oauth_token'], token['oauth_token_secret'], verify)
  login = flickr.test.login
  puts "You are now authenticated as #{login.username} with token #{flickr.access_token} and secret #{flickr.access_secret}"
rescue FlickRaw::FailedResponse => e
  puts "Authentication failed : #{e.msg}"
end
